import { INodeProperties } from 'n8n-workflow';

export const messageOperations: INodeProperties[] = [
    {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['message'] } },
        options: [
            { name: 'Send Text', value: 'sendText', action: 'Send text message' },
            { name: 'Send Media URL', value: 'sendMedia', action: 'Send media from URL' },
            { name: 'Send Location', value: 'sendLocation', action: 'Send location' },
            { name: 'Send Contact', value: 'sendContact', action: 'Send contact card' },
            { name: 'Send Poll', value: 'sendPoll', action: 'Send poll' },
            { name: 'Send List', value: 'sendList', action: 'Send list message' },
            { name: 'Send Sticker', value: 'sendSticker', action: 'Send sticker' },
            { name: 'Reply', value: 'reply', action: 'Reply to message' },
            { name: 'React', value: 'react', action: 'React to message' },
            { name: 'Star', value: 'star', action: 'Star or unstar message' },
            { name: 'Delete', value: 'delete', action: 'Delete message' },
            { name: 'Forward', value: 'forward', action: 'Forward message' },
            { name: 'Broadcast', value: 'broadcast', action: 'Broadcast message' },
            { name: 'Search', value: 'search', action: 'Search messages' },
            { name: 'Download Media', value: 'downloadMedia', action: 'Download media' },
            { name: 'Report Spam', value: 'spam', action: 'Report spam' },
        ],
        default: 'sendText',
    },
];

export const messageFields: INodeProperties[] = [
    { displayName: 'Text Message', name: 'text', type: 'string', typeOptions: { rows: 4 }, required: true, default: '', description: 'The text message payload to send', displayOptions: { show: { resource: ['message'], operation: ['sendText'] } } },
    { displayName: 'Media URL', name: 'mediaUrl', type: 'string', required: true, default: '', description: 'Direct URL to the image, video, audio, or document', displayOptions: { show: { resource: ['message'], operation: ['sendMedia'] } } },
    { displayName: 'Latitude', name: 'latitude', type: 'number', required: true, default: 0, description: 'Latitude coordinate (e.g. -6.2088)', displayOptions: { show: { resource: ['message'], operation: ['sendLocation'] } } },
    { displayName: 'Longitude', name: 'longitude', type: 'number', required: true, default: 0, description: 'Longitude coordinate (e.g. 106.8456)', displayOptions: { show: { resource: ['message'], operation: ['sendLocation'] } } },
    { displayName: 'Contacts (JSON)', name: 'contacts', type: 'string', typeOptions: { rows: 4 }, required: true, default: '[{"displayName": "John Doe", "vcard": "BEGIN:VCARD\\nVERSION:3.0\\nFN:John Doe\\nTEL;waid=1234567890:+1 234 567 890\\nEND:VCARD"}]', description: 'JSON array of contacts', displayOptions: { show: { resource: ['message'], operation: ['sendContact'] } } },
    { displayName: 'Poll Question', name: 'question', type: 'string', typeOptions: { rows: 2 }, required: true, default: '', description: 'The question to ask in the poll', displayOptions: { show: { resource: ['message'], operation: ['sendPoll'] } } },
    { displayName: 'Poll Options (Comma-separated)', name: 'pollOptions', type: 'string', required: true, default: '', description: 'Provide options separated by commas (e.g. Option 1, Option 2, Option 3)', displayOptions: { show: { resource: ['message'], operation: ['sendPoll'] } } },
    { displayName: 'List Title', name: 'listTitle', type: 'string', required: true, default: '', description: 'Main title of the list message', displayOptions: { show: { resource: ['message'], operation: ['sendList'] } } },
    { displayName: 'Button Text', name: 'listButtonText', type: 'string', required: true, default: 'Click Here', displayOptions: { show: { resource: ['message'], operation: ['sendList'] } } },
    { displayName: 'List Sections (JSON)', name: 'listSections', type: 'string', typeOptions: { rows: 4 }, required: true, default: '[{"title": "Section Title", "rows": [{"title": "Row Title", "rowId": "row1", "description": "Row desc"}]}]', description: 'JSON array of sections and rows', displayOptions: { show: { resource: ['message'], operation: ['sendList'] } } },
    { displayName: 'Sticker URL', name: 'stickerUrl', type: 'string', required: true, default: '', description: 'Direct URL to a WebP or compatible image to turn into a sticker', displayOptions: { show: { resource: ['message'], operation: ['sendSticker'] } } },
    { displayName: 'Target Message ID', name: 'messageId', type: 'string', required: true, default: '', description: 'The ID of the message to target', displayOptions: { show: { resource: ['message'], operation: ['reply', 'react', 'star', 'delete', 'downloadMedia'] } } },
    { displayName: 'Reply Text', name: 'replyText', type: 'string', typeOptions: { rows: 4 }, required: true, default: '', description: 'The text content of your reply', displayOptions: { show: { resource: ['message'], operation: ['reply'] } } },
    { displayName: 'Emoji Reaction', name: 'emoji', type: 'string', required: true, default: '', description: 'Emoji character to react with. Leave empty to remove an existing reaction.', displayOptions: { show: { resource: ['message'], operation: ['react'] } } },
    { displayName: 'Star Status', name: 'starValue', type: 'boolean', required: true, default: true, description: 'Whether to star or unstar', displayOptions: { show: { resource: ['message'], operation: ['star'] } } },
    { displayName: 'Target JID (To)', name: 'forwardToJid', type: 'string', required: true, default: '', description: 'JID of the recipient you are forwarding to', displayOptions: { show: { resource: ['message'], operation: ['forward'] } } },
    { displayName: 'Message ID to Forward', name: 'forwardMessageId', type: 'string', required: true, default: '', description: 'The ID of the message to forward', displayOptions: { show: { resource: ['message'], operation: ['forward'] } } },
    { displayName: 'Source JID (From)', name: 'forwardFromJid', type: 'string', required: true, default: '', description: 'JID of the chat containing the original message', displayOptions: { show: { resource: ['message'], operation: ['forward'] } } },
    { displayName: 'Broadcast Message', name: 'broadcastMsg', type: 'string', typeOptions: { rows: 4 }, required: true, default: '', description: 'The text message to broadcast to all recipients', displayOptions: { show: { resource: ['message'], operation: ['broadcast'] } } },
    { displayName: 'Recipients (Comma-separated JIDs)', name: 'recipients', type: 'string', required: true, default: '', description: 'Provide list of recipient JIDs separated by commas', displayOptions: { show: { resource: ['message'], operation: ['broadcast'] } } },

    {
        displayName: 'Additional Fields',
        name: 'additionalFields',
        type: 'collection',
        placeholder: 'Add Field',
        default: {},
        displayOptions: {
            show: {
                resource: ['message'],
                operation: ['sendText', 'sendMedia', 'sendLocation', 'sendPoll', 'sendList', 'sendSticker', 'reply', 'search'],
            },
        },
        options: [
            { displayName: 'Mentions (Comma-separated JIDs)', name: 'mentions', type: 'string', default: '', description: 'JIDs to mention separated by commas', displayOptions: { show: { '/operation': ['sendText', 'reply'] } } },
            { displayName: 'Caption', name: 'caption', type: 'string', typeOptions: { rows: 4 }, default: '', description: 'Text caption to accompany the media', displayOptions: { show: { '/operation': ['sendMedia'] } } },
            { displayName: 'Location Name', name: 'locationName', type: 'string', default: '', description: 'Display name of the place', displayOptions: { show: { '/operation': ['sendLocation'] } } },
            { displayName: 'Address', name: 'address', type: 'string', default: '', description: 'Address string of the place', displayOptions: { show: { '/operation': ['sendLocation'] } } },
            { displayName: 'Selectable Count', name: 'selectableCount', type: 'number', default: 1, description: 'Number of options a user is allowed to select', displayOptions: { show: { '/operation': ['sendPoll'] } } },
            { displayName: 'List Description', name: 'listDescription', type: 'string', typeOptions: { rows: 4 }, default: '', displayOptions: { show: { '/operation': ['sendList'] } } },
            { displayName: 'Sticker Pack Name', name: 'packName', type: 'string', default: 'WA-AKG', description: 'Name of the sticker pack metadata', displayOptions: { show: { '/operation': ['sendSticker'] } } },
            { displayName: 'Sticker Author', name: 'stickerAuthor', type: 'string', default: '', description: 'Author metadata on the sticker', displayOptions: { show: { '/operation': ['sendSticker'] } } },
            { displayName: 'Search Query', name: 'searchQuery', type: 'string', default: '', description: 'Text string to search for in messages', displayOptions: { show: { '/operation': ['search'] } } },
            { displayName: 'Filter by JID', name: 'filterJid', type: 'string', default: '', description: 'JID to restrict the search to a specific chat', displayOptions: { show: { '/operation': ['search'] } } },
        ],
    },
];
